### ISSUE TITLE
Unknown field "instance_vars"

### ISSUE THREAD

**Issue by sragha45** [concourse/examples#2]
Hi, 

Shouldn't the field for variables be "vars"? I see that currently we use "instance_vars" for specifying the variables, which causes the build to fail (Unknown field "instance_vars"). Should we change this to "vars"?

https://github.com/concourse/examples/blob/7208e3f1303d2027b30215fb939b081b89ca6b18/pipelines/set-pipelines.yml#L38

https://github.com/concourse/examples/blob/7208e3f1303d2027b30215fb939b081b89ca6b18/pipelines/set-pipelines.yml#L44

Thanks!

**Comment by taylorsilva** [comment]
Hey! This is a feature that's still on master and will be part of the next Concourse release. You can see how the job works here: https://ci.concourse-ci.org/teams/examples/pipelines/set-pipelines/jobs/set-example-pipelines/builds/24

Guess I was a bit premature on adding it to the repo but I wanted to play around with it a bit 😁

**Comment by sragha45** [comment]
Thanks for the update @taylorsilva
